#!/bin/sh

#########################################
# Connectivity


#########################################
# Commands to run apps

#########################################
# Commands to change dirs
alias to.dotfiles='cd ~/.dotfiles'
alias to.cloudbees='cd ~/Projects/CloudBees'
alias to.opensource='cd ~/Projects/Opensource'

#################################
# Simple Program Name Shortening
alias g=git

# Kubens / Kubectx
alias kns=kubens
alias kx=kubectx

# Maven daemon
alias m=mvnd
alias mqq='m -Pquick-build clean install'
alias mq='m clean install -DskipTests -Dinvoker.skip=true'
alias sl='m spotless:apply'
function spotless_git_setup() {
  local hooks="$(git rev-parse --git-path hooks)"
  local pre_commit_hook="$HOME/.dotfiles/git-hooks/spotless-pre-commit"
  if [ "$(readlink -f "$hooks/pre-commit")" = "$pre_commit_hook" ]; then
    echo "Spotless pre-commit hook already set up"
    return
  else
    echo "Setting up spotless pre-commit hook"
    rm -f "$hooks/pre-commit"
    ln -s "$pre_commit_hook" "$hooks/pre-commit"
  fi
}

# Helm
alias h=helm
alias h3=helm3

# CloudBees
alias cb=cloudbees

# AWS
alias aws.clusters='export AWS_PROFILE=cloudbees-cloud-platform-clusters; opscore iam refresh --role infra-admin --account $AWS_PROFILE'
alias aws.automation='export AWS_PROFILE=cloudbees-cloud-platform-cluster-automation; opscore iam refresh --role infra-admin --account $AWS_PROFILE'

#############################
# Utilities
alias zipall='for D in *; do zip -r "$D" "$D"; done'

alias pram.reset='sudo nvram boot-args=”-p -r”'

alias rubygems.update='sudo gem update --system'
alias brew.update='brew update && brew upgrade'

alias timemachine.enablelocalversions='sudo tmutil enablelocal'
alias timemachine.disablelocalversions='sudo tmutil disablelocal'

alias hexdumpfile='od -h'

alias uuid="uuidgen | tr -d '\n' | tr '[:upper:]' '[:lower:]'"

# Flush the DNS on Mac
alias network.dnsflush='dscacheutil -flushcache'

# Copy and paste and prune the usless newline
alias pbcopynn='tr -d "\n" | pbcopy'

# Set the extended MacOS attributes on a file such that Quicklook will open it as text
alias finder.astext='xattr -wx com.apple.FinderInfo "54 45 58 54 21 52 63 68 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00" $1'
#alias finder.qltext2='osascript -e tell application "Finder" to set file type of ((POSIX file "$1") as alias) to "TEXT"'

# Git
function git-cleanup() {
  git cleanup
  local main_branch; main_branch="$(git rev-parse --abbrev-ref HEAD)"
  git checkout -q $main_branch && git for-each-ref refs/heads/ "--format=%(refname:short)" | while read branch; do mergeBase=$(git merge-base $main_branch $branch) && [[ $(git cherry $main_branch $(git commit-tree $(git rev-parse "$branch^{tree}") -p $mergeBase -m _)) == "-"* ]] && git branch -D $branch; done
}

# Show network connections
# Often useful to prefix with SUDO to see more system level network usage
alias network.connections='lsof -l -i +L -R -V'
alias network.established='lsof -l -i +L -R -V | grep ESTABLISHED'
alias network.internalip="ifconfig en0 | egrep -o '([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)'"
alias network.externalip='curl -s http://checkip.dyndns.org/ | sed "s/[a-zA-Z<>/ :]//g"'

# Files used, anywhere on the filesystem
alias files.usage='sudo fs_usage -e -f filesystem|grep -v CACHE_HIT|grep -v grep'
# Files being opened
alias files.open='sudo fs_usage -e -f filesystem|grep -v CACHE_HIT|grep -v grep|grep open'
# Files in use in the Users directory
alias files.usage.user='sudo fs_usage -e -f filesystem|grep -v CACHE_HIT|grep -v grep|grep Users'

# Directory listings
LS_COLORS='no=01;37:fi=01;37:di=07;96:ln=01;36:pi=01;32:so=01;35:do=01;35:bd=01;33:cd=01;33:ex=01;31:mi=00;05;37:or=00;05;37:'
# -G Add colors to ls
# -l Long format
# -h Short size suffixes (B, K, M, G, P)
# -p Postpend slash to folders
alias ls='ls --color -h -p '
alias ll='ls -l --color -h -p '

alias incremental.version='gh pr checks | grep incrementals | rev | cut -d '/' -f 2 | rev'

#########################################
# Utility Functions

# Do a Matrix movie effect of falling characters
function matrix1() {
echo -e "\e[1;40m" ; clear ; while :; do echo $LINES $COLUMNS $(( $RANDOM % $COLUMNS)) $(( $RANDOM % 72 )) ;sleep 0.05; done|gawk '{ letters="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789@#$%^&*()"; c=$4; letter=substr(letters,c,1);a[$3]=0;for (x in a) {o=a[x];a[x]=a[x]+1; printf "\033[%s;%sH\033[2;32m%s",o,x,letter; printf "\033[%s;%sH\033[1;37m%s\033[0;0H",a[x],x,letter;if (a[x] >= $1) { a[x]=0; } }}'
}

function matrix2() {
echo -e "\e[1;40m" ; clear ; characters=$( jot -c 94 33 | tr -d '\n' ) ; while :; do echo $LINES $COLUMNS $(( $RANDOM % $COLUMNS)) $(( $RANDOM % 72 )) $characters ;sleep 0.05; done|gawk '{ letters=$5; c=$4; letter=substr(letters,c,1);a[$3]=0;for (x in a) {o=a[x];a[x]=a[x]+1; printf "\033[%s;%sH\033[2;32m%s",o,x,letter; printf "\033[%s;%sH\033[1;37m%s\033[0;0H",a[x],x,letter;if (a[x] >= $1) { a[x]=0; } }}'
}

function matrix3() {
echo -e "\e[1;40m" ; clear ; while :; do echo $LINES $COLUMNS $(( $RANDOM % $COLUMNS)) $( printf "\U$(( $RANDOM % 500 ))" ) ;sleep 0.05; done|gawk '{c=$4; letter=$4;a[$3]=0;for (x in a) {o=a[x];a[x]=a[x]+1; printf "\033[%s;%sH\033[2;32m%s",o,x,letter; printf "\033[%s;%sH\033[1;37m%s\033[0;0H",a[x],x,letter;if (a[x] >= $1) { a[x]=0; } }}'
}

# Remap the key above tab from my US internal keyboard to backtick
function remapUsInternationalKeyboard() {
  sudo hidutil property --set '{"UserKeyMapping":
    [{"HIDKeyboardModifierMappingSrc":0x700000064,
      "HIDKeyboardModifierMappingDst":0x700000035}]
  }'
}

function remapCancelUsInternationalKeyboard() {
  sudo hidutil property --set '{"UserKeyMapping":
    [{"HIDKeyboardModifierMappingSrc":0x700000064,
      "HIDKeyboardModifierMappingDst":0x700000064}]
  }'
}

# Show normally hidden system and dotfile types of files
# in Mac OSX Finder
function finder.showhiddenfiles() {
  defaults write com.apple.Finder AppleShowAllFiles YES
  osascript -e 'tell application "Finder" to quit'
  sleep 0.25
  osascript -e 'tell application "Finder" to activate'
}

# Hide (back to defaults) normally hidden system and dotfile types of files
# in Mac OSX Finder
function finder.hidehiddenfiles() {
  defaults write com.apple.Finder AppleShowAllFiles NO
  osascript -e 'tell application "Finder" to quit'
  sleep 0.25
  osascript -e 'tell application "Finder" to activate'
}

# Get (cache) all Cheat sheets
function cheat.getall() {
	cheat sheets | grep '^  ' | xargs -n 1 -I {} bash -c 'cheat {} | :'
}

function find.name() {
  wild=\'\*$1\*\'
  sh -c "find . -iname $wild"
}

alias lessc='less -R' # Lets color escape sequences carry through to less
alias morec='more -R'
alias lesscolor='less -R'
alias morecolor='more -R'

function screenshot.setjpg() {
    defaults write com.apple.screencapture type jpg
    killall SystemUIServer
}

function screenshot.setpng() {
    defaults write com.apple.screencapture type png
	killall SystemUIServer
}

alias ecr-login-gauntlet='opscore ecr login --account cloudbees-gauntlet --role infra-ecr-reader'

function jwtd() {
    if [[ -x $(command -v jq) ]]; then
         cat - | jq -R 'split(".") | .[0],.[1] | @base64d | fromjson'
         echo "Signature: $(echo "${1}" | awk -F'.' '{print $3}')"
    fi
}

function login_ecr() {
  if [ "$#" -lt 1 ]; then
    echo "Usage: login_ecr <profile> [tool=docker,helm,skopeo...]"
    return 1
  fi
  export AWS_PROFILE=${1:?}
  export AWS_DEFAULT_REGION=us-east-1
  tool="${2:-docker}"
  if [ "$tool" = "helm" ]
  then
    toolcmd="helm registry"
  else
    toolcmd="$tool"
  fi
  aws sso login
  aws ecr get-login-password | ${=toolcmd} login --username AWS --password-stdin $(aws sts get-caller-identity --query Account --output text).dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
}

function clone() {
  projectsHome=~/projects/github.com
  orgs=(calculi-corp cloudbees-io cloudbees jenkinsci)

  if [ "$#" -ne 1 ]; then
      echo "Clones a given github repository to $projectsHome/ORG/REPO"
      echo "Usage: clone [ORG/]<REPO> or clone <URL>"
      return 0
  fi
  if [[ $1 =~ 'https://github.com/([^;]+)/([^;]+)' || $1 =~ '([^;]+)/([^;]+)' ]]; then
      org=$match[1]
      repo=${match[2]%".git"} # Remove .git suffix if it exists
  else
      repo=$1
      for org in "${orgs[@]}"; do
          echo "Trying $org org"
          if clone $org/$repo; then
              return 0
          fi
      done
      return 0
  fi

  if ! [ -d "$projectsHome/$org/$repo" ]; then
      gh repo clone $org/$repo "$projectsHome/$org/$repo" -- --recurse-submodules
  else
      echo "$projectsHome/$org/$repo already exists; pulling"
      (cd "$projectsHome/$org/$repo"; git pull)
  fi
  if ! [ -d "$projectsHome/$org/$repo" ]; then
    return 1
  else
    cd "$projectsHome/$org/$repo"
  fi
  [ "$(gh repo set-default --view)" != "$org/$repo" ] && gh repo set-default $org/$repo
  [ -f .gitmodules ] && git submodule update --init
  gh repo fork --remote --clone
  spotless_git_setup
}

function link_war_trad() {
  current=$(basename $(pwd))
  echo $current
  URR_HOME="$HOME/projects/github.com/cloudbees/unified-release"
  if [ "$current" = "je-acceptance-test" ]; then
    ln -sf $URR_HOME/products/core-cm/target/*.war jenkins.war
  fi
  if [ "$current" = "operations-center-acceptance-test" ]; then
    ln -sf $URR_HOME/products/core-cm/target/*.war je.war
    ln -sf $URR_HOME/products/core-oc-traditional/target/*.war jenkins-oc.war
  fi
}

function link_war_modern() {
  current=$(basename $(pwd))
  echo $current
  URR_HOME="$HOME/projects/github.com/cloudbees/unified-release"
  if [ "$current" = "je-acceptance-test" ]; then
    ln -sf $URR_HOME/products/core-mm/target/*.war jenkins.war
  fi
  if [ "$current" = "operations-center-acceptance-test" ]; then
    ln -sf $URR_HOME/products/core-mm/target/*.war je.war
    ln -sf $URR_HOME/products/core-oc/target/*.war jenkins-oc.war
  fi
}

function cbci_password() {
  kubectl exec cjoc-0 -- cat /var/jenkins_home/secrets/initialAdminPassword | pbcopy
  echo "Operations Center password copied to clipboard"
}

function set_up_debug_cjoc() {
  local pods; pods=($(kubectl get po -l com.cloudbees.cje.tenant=cjoc -o name))
  local port=4005
  for pod in $pods; do
    debug_clean $port
    kubectl port-forward $pod $port:5005 &
    port=$((port+1))
  done
}

function set_up_debug() {
  local pods; pods=($(kubectl get po -l tenant=mc -o name))
  local port=5005
  for pod in $pods; do
    debug_clean $port
    kubectl port-forward $pod $port:5005 &
    port=$((port+1))
  done
}

function set_up_jmx() {
  local pods; pods=($(kubectl get po -l tenant=mc -o name))
  local port=4000
  for pod in $pods; do
    debug_clean $port
    kubectl port-forward $pod $port:4000 &
    port=$((port+1))
  done
}

function debug_clean() {
  local port="${1:?}"
  old_pid=$(lsof -ti tcp:$port)
  if [ -n "$old_pid" ]; then
    echo "Killing $old_pid as it is using port $port"
    kill -9 $old_pid
  fi
}